### ISSUE TITLE
Add image hover animation

### ISSUE THREAD

**Issue by Knochenmark** [JutJut/svelte-kit-level-2#10]
Consider a mixin or wrapper component for reusability.

example css:
````css
  .your-selector {
    transition: transform var(--transition-fast) ease-in-out !important;
  }

  &:hover .your-selector {
    transform: scale(1.1);
  }
```
